<div id="productos">
    
    <div class="row medium-up-3 large-up-5">
   {% for prod in productos %}
       <div class="column" >
           <h5>{{ prod.producto }}</h5>
           <p> {{ prod.descripcion }}</p>
           <p><strong>Cant:</strong> {{ prod.unidades }}  </p>
           <h3><small>${{ prod.valor }}</small></h3>
           <a href="#" class="button hollow tiny expanded">Buy Now</a>
       </div>
    {% endfor %}
    </div>
</div>