<div class="row">

    <div class="small-12 medium-6 columns">

        {{ form('session/start', 'method': 'post') }}
        
            {% for field in form %}
        
                {% set messages = form.getMessagesFor(field.getName()) %}

                {% if messages|length > 0 %}
                    <div class="messages alert callout">
                        {% for message in  messages %}
                            <div class="message">
                              <p>{{ message }}</p>
                            </div>
                        {% endfor%}
                    </div>
                {% endif %}
                <div class="row">
                     <label for="{{ field.getName() }}"> {{ field.getLabel() }}
                     {{ field  }}
                      </label>
                </div>
            {% endfor %}
             <div class="row">
                <div class="small-12 medium-6">
                    {{ submit_button('Login','class' : 'button text-center') }}
                </div>   
             </div>
        {{ end_form() }}
    </div>          

</div>