<!DOCTYPE html>
<html>
    <head>
        <title>I'am Phalcon</title>
    </head>
    <body>
        <div class="menu">
            <ul>
                <li><a href="#">Inicio</a></li>
                <li><a href="#">Quien es phalcon</a></li>
                <li><a href="#">Siza</a></li>
            </ul> 
        </div>
        
        <div class="main">
                <?php echo $this->getContent(); ?>
        </div>
        <class="footer">
         <ul>
             <li>Redes</li>
             <li>Cumbia</li>
             <li>Toma todo mi dinero</li>
             
         </ul>
            
        </class>

    </body>
</html>