{% extends "layouts/__main.phtml" %}
{% block title %} {{titulo}} {% endblock %}
{% block content %}
    <div class="column row">
        <hr>
        <article class="small-12 columns">
            <header>
                <h1>{{titulo}}</h1>
            </header>
            <section>
                <?php echo $this->getContent(); ?>
            </section>
        </article>
    </div>
{% endblock %}